version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: raksha-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: raksha-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  inspection-backend:
    build:
      context: .
      dockerfile: Dockerfile.inspection
    container_name: raksha-inspection-backend
    ports:
      - "5001:5001"
    restart: unless-stopped