FROM node:20-alpine

WORKDIR /app

COPY inspectionBackend/package*.json ./

RUN npm install

COPY inspectionBackend/. .

RUN addgroup -S app && adduser -S app -G app

USER app

EXPOSE 5001

CMD ["node", "server.js"]
