FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /etc/nginx/conf.d/default.conf

COPY *.html /usr/share/nginx/html/

COPY docker/nginx/frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80